<package format="2">
  <name>airseai_navigation</name>
  <version>0.0.0</version>
  <description>Airseai Navigation Package</description>

  <maintainer email="airseai@cuhk.edu.cn">your_name</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclpy</build_depend>
  <build_depend>airseai_interface</build_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>airseai_interface</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
